const ACCOUNTS = [
    { name: "Kasse", aliases: ["Ka"] },
    { name: "Bank", aliases: ["Ba"] },
    { name: "Forderungen aus Lieferungen und Leistungen", aliases: ["Ford. L+L", "FLL"] },
    { name: "Verbindlichkeiten aus Lieferungen und Leistungen", aliases: ["Verb. L+L", "VLL"] },
    { name: "Eigenkapital", aliases: ["EK"] },
    { name: "Umsatzerlöse", aliases: ["UE"] },
    { name: "Materialaufwand", aliases: ["MA"] },
    { name: "Personalaufwand", aliases: ["PA"] },

    /* Aktive */
    { name: "Post"},
    { name: "Aktive Rechnungsabgrenzungen", aliases: ["ARA","Aktive RA"] },
    { name: "Wertschriften", aliases: ["WS"] },
    { name: "Vorsteuer MWST 1170", aliases: ["Vorsteuer 1170", "Vorst. 1170"] },
    { name: "Vorsteuer MWST 1171", aliases: ["Vorsteuer 1171", "Vorst. 1171"] },
    { name: "Forderung Verrechnungssteuer", aliases: ["Ford. VST", "Forderung VST."] },
    { name: "Warenvorrat", aliases: ["Vorrat", "WaV"] },
    { name: "Werteberichtigungen Forderungen(Delkredere)", aliases: ["WB Forderungen", "WB Ford.", "Werteberichtigung Forderungen"] },
    { name: "Aktivdarlehen", aliases: ["AktivD"] },
    { name: "Maschinen", aliases: ["Masch.", "Masch"] },
    { name: "Werteberichtigung Maschinen", aliases: ["WB Masch.", "WB Maschinen"] },
    { name: "Mobiliar und Einrichtungen", aliases: ["Mobiliar","Mob"] },
    { name: "Werteberichtigung Mobiliar und Einrichtungen", aliases: ["WB Mobiliar","WB Mob"] },
    { name: "Werteberichtigung Fahrzeuge", aliases: ["WB Fahrzeuge","WB Fz"] },
    { name: "Fahrzeuge", aliases: ["Fz"] },
    { name: "Liegenschaften", aliases: ["Lg"] },
    { name: "Werteberichtigung Liegenschaften", aliases: ["WB Liegenschaften","WB Lg"] },
    { name: "Werteberichtigung Liegenschaften", aliases: ["WB Liegenschaften","WB Lg"] },

    /*Pasive*/
    { name: "Verbindlichkeiten MWST", aliases: ["Verb. MWST"] },
    { name: "Verbindlichkeiten Verechnungssteuer", aliases: ["Verb. Verechnungssteuer","Verb. VST."] },
    { name: "Dividenden"},
    { name: "Verbindlichkeiten Sozialversicherungen", aliases: ["Verb. Sozialversicherungen", "Verb. Soz. vers.", "Verb. Sozialvers."]},
    { name: "Passive Rechnungsabgrenzungen", aliases: ["Passive RA", "PRA"]},
    { name: "Rückstellungen", aliases: ["Rs"]},
    { name: "Hypotheken", aliases: ["Hypo"]},
    { name: "Passivdarlehen", aliases: ["PassivD"]},
    { name: "Aktienkapital", aliases: ["AK"]},
    { name: "Gesetzliche Gewinnreserve", aliases: ["Ges. Gewinnres.", "Gesetzliche Gewinnres."]},
    { name: "Gewinnvortrag"},
    { name: "Jahresgewinn"},
    { name: "Privat"},

    /*Erträge*/
    { name: "Produktionserlöse", aliases: ["ProduktionsE","ProdE"] },
    { name: "Warenerlöse", aliases: ["WarenE","WaE"] },
    { name: "Dienstleistungserlöse", aliases: ["DLE","DienstleistungsE"] },
    { name: "Übrige Erlöse", aliases: ["Übr. Erlöse","Übr. E."] },
    { name: "Verluste aus Forderungen", aliases: ["Verl. Ford.","Verl. aus Ford.","Verluste Forderungen"] },
    { name: "Finanzertrag", aliases: ["FinE","FinanzE"] },
    { name: "Liegenschaftsertrag", aliases: ["LiegenschaftsE","LgE"] },
    { name: "Ausserordentlicher Ertrag", aliases: ["A.o. Ertrag","A.o. E."] },


    /*Aufwände*/
    { name: "Materialaufwand", aliases: ["MaterialA","MA"] },
    { name: "Warenaufwand", aliases: ["WarenA","WaA"] },
    { name: "Lohnaufwand", aliases: ["LohnA"] },
    { name: "Sozialversicherungsaufwand", aliases: ["Soz. VersA","Soz. Vers. Aufwand"] },
    { name: "Übriger Personalaufwand", aliases: ["Übr. Personalaufwand","Übr. PersA"] },
    { name: "Raumaufwand", aliases: ["RaumA"] },
    { name: "Reparaturen"},
    { name: "Fahrzeugaufwand", aliases: ["FzA", "FahrzeugA"]},
    { name: "Versicherungsaufwand", aliases: ["VersA"]},
    { name: "Energieaufwand", aliases: ["EnergieA"]},
    { name: "Verwaltungsaufwand", aliases: ["VerwaltungsA","VerwA"]},
    { name: "Werbeaufwand", aliases: ["WerbeA"]},
    { name: "Sonstiger Betriebsaufwand", aliases: ["Sonst. BA"]},
    { name: "Abschreibungen", aliases: ["Abschr."]},
    { name: "Finanzaufwand", aliases: ["FinanzA","FinA"]},
    { name: "Liegenschaftsaufwand", aliases: ["LiegenschaftsA","LgA"]},
    { name: "Betriebsfremder Aufwand", aliases: ["Betriebsfremder A"]},
    { name: "Ausserordentlicher Aufwand", aliases: ["A.o. Aufwand", "A.o. A."]},

    /* TODO: all accounts ... */
];

export default ACCOUNTS;